#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'minimumAbsoluteDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def minimumAbsoluteDifference(arr):
    # Write your code here
    
    min_abs_diff=math.inf
    
    arr=sorted(arr)
    
    for i in range(0,len(arr)-1):
        
        diff=abs(arr[i]-arr[i+1])
        if diff<min_abs_diff:
            min_abs_diff=diff
            if min_abs_diff==0:
                return 0
            
    return min_abs_diff

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = minimumAbsoluteDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
