#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'luckBalance' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER k
#  2. 2D_INTEGER_ARRAY contests
#

def luckBalance(k, contests):
    # Write your code here
    
    important_contest=[]
    not_important_contest=[]

    luck=0

    for each in contests:
        if each[1]==1:
            important_contest.append(each[0])
        else:
            not_important_contest.append(each[0])

    important_contest=sorted(important_contest,reverse=True)

    luck=sum(not_important_contest)+sum(important_contest[:k])-sum(important_contest[k:])

    #print(important_contest)

    return luck

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    k = int(first_multiple_input[1])

    contests = []

    for _ in range(n):
        contests.append(list(map(int, input().rstrip().split())))

    result = luckBalance(k, contests)

    fptr.write(str(result) + '\n')

    fptr.close()
