#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the getMinimumCost function below.
def getMinimumCost(k, c):
    
    c=sorted(c,reverse=True)
    
    iterx=-1
    cost=0
    
    for i in range(0,len(c)):
        if i%k==0:
            iterx+=1
        cost+=(iterx+1)*c[i]
        
    return cost
            
        
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = input().split()

    n = int(nk[0])

    k = int(nk[1])

    c = list(map(int, input().rstrip().split()))

    minimumCost = getMinimumCost(k, c)

    fptr.write(str(minimumCost) + '\n')

    fptr.close()
