#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'maxMin' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER k
#  2. INTEGER_ARRAY arr
#

def maxMin(k, arr):
    # Write your code here
    unfairmess_ratio=math.inf
    
    arr=sorted(arr)
    
    print(arr)
    for i in range(0,len(arr)-k+1):
        if arr[i+k-1]-arr[i]<unfairmess_ratio:
            unfairmess_ratio=arr[i+k-1]-arr[i]
            
    return unfairmess_ratio

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    k = int(input().strip())

    arr = []

    for _ in range(n):
        arr_item = int(input().strip())
        arr.append(arr_item)

    result = maxMin(k, arr)

    fptr.write(str(result) + '\n')

    fptr.close()
